#!/usr/bin/python3
def raise_exception():
    one = 'i'
    two = 2
    result = one + two 
    return result
